import { NextRequest } from "next/server";
import { successResponse, errorResponse, parseBody, getPaginationParams } from "@/lib/api/utils";
import { addBranchSchema } from "@/lib/validations/auth";
import { branchService, auditService } from "@/modules/services";
import { getRequestUser, getRequestIp } from "@/lib/api/auth-helpers";
import { requireSession } from "@/lib/api/require-auth";
import { UserModel } from "@/modules/database/models";
import { hashPassword } from "@/modules/database/password";
import { generateId } from "@/modules/database/repositories/base.repository";

// GET /api/branches - List all branches
export async function GET(request: NextRequest) {
  try {
    const auth = await requireSession(["super_admin", "branch_admin"]);
    if ("response" in auth) return auth.response;

    if (auth.session.role === "branch_admin") {
      const branchId = auth.session.branchId;
      if (!branchId) {
        return errorResponse("Branch not assigned", 403);
      }

      const result = await branchService.getBranch(branchId);
      if (!result.success || !result.data) {
        return errorResponse(result.error || "Branch not found", 404);
      }

      return successResponse({
        data: [result.data],
        total: 1,
        page: 1,
        pageSize: 1,
        totalPages: 1,
      });
    }

    const { searchParams } = new URL(request.url);
    const pagination = getPaginationParams(searchParams);

    const filters = {
      status: searchParams.get("status") || undefined,
      search: searchParams.get("search") || undefined,
    };

    const result = await branchService.getBranches(filters, pagination);
    return successResponse(result);

  } catch (error) {
    console.error("Get branches error:", error);
    return errorResponse("Failed to fetch branches", 500);
  }
}

// POST /api/branches - Create a new branch
export async function POST(request: NextRequest) {
  try {
    const auth = await requireSession(["super_admin"]);
    if ("response" in auth) return auth.response;

    const body = await parseBody<Record<string, unknown>>(request);

    if (!body) {
      return errorResponse("Invalid request body");
    }

    const validation = addBranchSchema.safeParse(body);
    if (!validation.success) {
      const issues = validation.error.issues;
      return errorResponse(issues[0]?.message || "Validation failed", 422);
    }

    const result = await branchService.createBranch({
      name: validation.data.name,
      address: validation.data.address,
      city: validation.data.city,
      state: validation.data.state,
      phone: validation.data.phone,
      email: validation.data.email,
    });

    if (!result.success) {
      return errorResponse(result.error || "Failed to create branch", 409);
    }

    const actor = await getRequestUser();
    const ipAddress = getRequestIp(request);

    // Auto-create branch admin if user doesn't exist
    let adminCreated = false;
    try {
      if (result.data) {
        const email = result.data.email.toLowerCase();
        const existingUser = await UserModel.findOne({ email }).lean();

        if (!existingUser) {
          const now = new Date().toISOString();
          const passwordHash = await hashPassword("admin123");

          const adminUser = await UserModel.create({
            id: generateId("USR"),
            name: `${result.data.name} Admin`,
            email,
            phone: result.data.phone,
            role: "branch_admin",
            branchId: result.data.id,
            passwordHash,
            createdAt: now,
            updatedAt: now,
          });

          adminCreated = true;

          // Audit the user creation too
          auditService.logAction({
            userId: actor.userId,
            userName: actor.userName,
            action: "create_admin_user",
            resource: "admin_user",
            resourceId: adminUser.id,
            details: {
              email: adminUser.email,
              branchId: result.data.id,
              autoGenerated: true
            },
            ipAddress,
            branchId: result.data.id,
          });
        }
      }
    } catch (err) {
      console.error("Failed to auto-create branch admin:", err);
      // Don't fail the request, just log it. Branch was created successfully.
    }

    if (result.data) {
      auditService.logAction({
        userId: actor.userId,
        userName: actor.userName,
        action: "create_branch",
        resource: "branch",
        resourceId: result.data.id,
        details: result.data as unknown as Record<string, unknown>,
        ipAddress,
        branchId: result.data.id,
      });
    }

    const message = adminCreated
      ? "Branch created successfully. Admin credentials generated (Password: admin123)."
      : "Branch created successfully.";

    return successResponse(result.data, message, 201);

  } catch (error) {
    console.error("Create branch error:", error);
    return errorResponse("Failed to create branch", 500);
  }
}
